### ISSUE TITLE
JSX files present in dist

### ISSUE THREAD

**Issue by wakaztahir** [solidjs-community/tsup-preset-solid#7]
When I build the tsx files get built and they become jsx files into dist folder which then cause errors like this on build where library is consumed

I am trying to build a solid-start project which consumes a library that is published using this preset with tsup, That library contains jsx

The library is <a href="https://github.com/Qinetik/anique">`@qinetik/anique-icons`</a>, only contains 4 icons at the moment

```
Error [RollupError]: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.tryParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14476:25)
    at Module.setSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
    at ModuleLoader.addModuleSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:24649:20) {
  cause: SyntaxError: Unexpected token (3:9)
      at pp$4.raise (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
      at pp$9.unexpected (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18829:8)
      at pp$5.parseExprAtomDefault (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20990:8)
      at pp$5.parseExprAtom (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20985:17)
      at pp$5.parseExprSubscripts (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20769:19)
      at pp$5.parseMaybeUnary (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20735:17)
      at pp$5.parseExprOps (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20662:19)
      at pp$5.parseMaybeConditional (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20645:19)
      at pp$5.parseMaybeAssign (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20612:19)
      at pp$5.parseExpression (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20575:19)
      at pp$8.parseReturnStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19149:31)
      at pp$8.parseStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18977:37)
      at pp$8.parseBlock (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19311:21)
      at pp$5.parseFunctionBody (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:21440:22)
      at pp$8.parseFunction (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19433:8)
      at pp$8.parseFunctionStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19127:15)
      at pp$8.parseStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18972:17)
      at pp$8.parseTopLevel (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18886:21)
      at Parser.parse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18658:15)
      at Function.parse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18708:35)
      at Graph.contextParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:25754:38)
      at Module.tryParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14473:31)
      at Module.setSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
      at ModuleLoader.addModuleSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:24649:20) {
    pos: 53,
    loc: Position { line: 3, column: 9 },
    raisedAt: 54
  },
  code: 'PARSE_ERROR',
  id: 'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
  pos: 53,
  loc: {
    column: 9,
    file: 'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
    line: 3
  },
  frame: '1: // src/AlertIcon.tsx\n' +
    '2: function AlertIcon() {\n' +
    '3:   return <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">\n' +
    '            ^\n' +
    '4:     <title>alert</title>\n' +
    '5:     <path d="M13 14H11V9H13M13 18H11V16H13M1 21H23L12 2L1 21Z" />',
  watchFiles: [
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\.solid\\server\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\dist\\public\\route-manifest.json',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\.solid\\server\\entry-server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-start\\node\\globals.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-start\\node\\fetch.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-js\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\typescript-cookie\\dist\\typescript-cookie.mjs',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-js\\web\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\emotion\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\seroval\\dist\\esm\\production\\index.mjs',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@emotion\\serialize\\dist\\emotion-serialize.esm.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@emotion\\is-prop-valid\\dist\\emotion-is-prop-valid.esm.js'
  ]
}

Node.js v20.7.0
```

Shouldn't this preset use babel to transform the JSX files

**Comment by thetarnav** [comment]
> Shouldn't this preset use babel to transform the JSX files

It does, and it doesn't.
The default export should contain the library with jsx compiled for client-side rendering.
And preserved jsx is only accessed under the `solid` export condition, used by solid vite plugin, and solid start.
Outputting jsx files is intended. Solid has various compilation targets. Libraries need to ship preserved jsx, so the application can compile it to the correct target.

**Comment by wakaztahir** [comment]
I used rollup to with babel-preset-solid

**Comment by thetarnav** [comment]
I see, closing this then
